export default {
    FETCH_USER_PROFILE_LOADING: 'FETCH_USER_PROFILE_LOADING',
    FETCH_USER_PROFILE_FAILED: 'FETCH_USER_PROFILE_FAILED',
    FETCH_USER_PROFILE_REJECTED: 'FETCH_USER_PROFILE_REJECTED',
    FETCH_USER_PROFILE_SUCCESSFULLY: 'FETCH_USER_PROFILE_SUCCESSFULLY',


    IS_USER_ALLOWED_TO_SEND_MESSAGE_LOADING: 'IS_USER_ALLOWED_TO_SEND_MESSAGE_LOADING',
    IS_USER_ALLOWED_TO_SEND_MESSAGE_FAILED: 'IS_USER_ALLOWED_TO_SEND_MESSAGE_FAILED',
    IS_USER_ALLOWED_TO_SEND_MESSAGE_REJECTED: 'IS_USER_ALLOWED_TO_SEND_MESSAGE_REJECTED',
    IS_USER_ALLOWED_TO_SEND_MESSAGE_SUCCESSFULLY: 'IS_USER_ALLOWED_TO_SEND_MESSAGE_SUCCESSFULLY',


    FETCH_PROFILE_STATISTICS_LOADING: 'FETCH_PROFILE_STATISTICS_LOADING',
    FETCH_PROFILE_STATISTICS_FAILED: 'FETCH_PROFILE_STATISTICS_FAILED',
    FETCH_PROFILE_STATISTICS_REJECTED: 'FETCH_PROFILE_STATISTICS_REJECTED',
    FETCH_PROFILE_STATISTICS_SUCCESSFULLY: 'FETCH_PROFILE_STATISTICS_SUCCESSFULLY',


    FETCH_PROFILE_BY_USERNAME_LOADING: 'FETCH_PROFILE_BY_USERNAME_LOADING',
    FETCH_PROFILE_BY_USERNAME_FAILED: 'FETCH_PROFILE_BY_USERNAME_FAILED',
    FETCH_PROFILE_BY_USERNAME_REJECT: 'FETCH_PROFILE_BY_USERNAME_REJECT',
    FETCH_PROFILE_BY_USERNAME_SUCCESSFULLY: 'FETCH_PROFILE_BY_USERNAME_SUCCESSFULLY',


    FETCH_PRODUCTS_LIST_BY_USERNAME_LOADING: 'FETCH_PRODUCTS_LIST_BY_USERNAME_LOADING',
    FETCH_PRODUCTS_LIST_BY_USERNAME_FAILED: 'FETCH_PRODUCTS_LIST_BY_USERNAME_FAILED',
    FETCH_PRODUCTS_LIST_BY_USERNAME_REJECTED: 'FETCH_PRODUCTS_LIST_BY_USERNAME_REJECTED',
    FETCH_PRODUCTS_LIST_BY_USERNAME_SUCCESSFULLY: 'FETCH_PRODUCTS_LIST_BY_USERNAME_SUCCESSFULLY',
}