export default {
    FETCH_USER_PROFILE_LOADING: 'FETCH_USER_PROFILE_LOADING',
    FETCH_USER_PROFILE_FAILED: 'FETCH_USER_PROFILE_FAILED',
    FETCH_USER_PROFILE_REJECTED: 'FETCH_USER_PROFILE_REJECTED',
    FETCH_USER_PROFILE_SUCCESSFULLY: 'FETCH_USER_PROFILE_SUCCESSFULLY',


    IS_USER_ALLOWED_TO_SEND_MESSAGE_LOADING: 'IS_USER_ALLOWED_TO_SEND_MESSAGE_LOADING',
    IS_USER_ALLOWED_TO_SEND_MESSAGE_FAILED: 'IS_USER_ALLOWED_TO_SEND_MESSAGE_FAILED',
    IS_USER_ALLOWED_TO_SEND_MESSAGE_REJECTED: 'IS_USER_ALLOWED_TO_SEND_MESSAGE_REJECTED',
    IS_USER_ALLOWED_TO_SEND_MESSAGE_SUCCESSFULLY: 'IS_USER_ALLOWED_TO_SEND_MESSAGE_SUCCESSFULLY',
}