export default {
    FETCH_USER_PROFILE_LOADING: 'FETCH_USER_PROFILE_LOADING',
    FETCH_USER_PROFILE_FAILED: 'FETCH_USER_PROFILE_FAILED',
    FETCH_USER_PROFILE_REJECT: 'FETCH_USER_PROFILE_REJECT',
    FETCH_USER_PROFILE_SUCCESSFULLY: 'FETCH_USER_PROFILE_SUCCESSFULLY',


    IS_USER_ALLOWED_TO_SEND_MESSAGE_LOADING: 'IS_USER_ALLOWED_TO_SEND_MESSAGE_LOADING',
    IS_USER_ALLOWED_TO_SEND_MESSAGE_FAILED: 'IS_USER_ALLOWED_TO_SEND_MESSAGE_FAILED',
    IS_USER_ALLOWED_TO_SEND_MESSAGE_REJECT: 'IS_USER_ALLOWED_TO_SEND_MESSAGE_REJECT',
    IS_USER_ALLOWED_TO_SEND_MESSAGE_SUCCESSFULLY: 'IS_USER_ALLOWED_TO_SEND_MESSAGE_SUCCESSFULLY',


    FETCH_PROFILE_STATISTICS_LOADING: 'FETCH_PROFILE_STATISTICS_LOADING',
    FETCH_PROFILE_STATISTICS_FAILED: 'FETCH_PROFILE_STATISTICS_FAILED',
    FETCH_PROFILE_STATISTICS_REJECT: 'FETCH_PROFILE_STATISTICS_REJECT',
    FETCH_PROFILE_STATISTICS_SUCCESSFULLY: 'FETCH_PROFILE_STATISTICS_SUCCESSFULLY',


    FETCH_PROFILE_BY_USERNAME_LOADING: 'FETCH_PROFILE_BY_USERNAME_LOADING',
    FETCH_PROFILE_BY_USERNAME_FAILED: 'FETCH_PROFILE_BY_USERNAME_FAILED',
    FETCH_PROFILE_BY_USERNAME_REJECT: 'FETCH_PROFILE_BY_USERNAME_REJECT',
    FETCH_PROFILE_BY_USERNAME_SUCCESSFULLY: 'FETCH_PROFILE_BY_USERNAME_SUCCESSFULLY',


    FETCH_PRODUCTS_LIST_BY_USERNAME_LOADING: 'FETCH_PRODUCTS_LIST_BY_USERNAME_LOADING',
    FETCH_PRODUCTS_LIST_BY_USERNAME_FAILED: 'FETCH_PRODUCTS_LIST_BY_USERNAME_FAILED',
    FETCH_PRODUCTS_LIST_BY_USERNAME_REJECT: 'FETCH_PRODUCTS_LIST_BY_USERNAME_REJECT',
    FETCH_PRODUCTS_LIST_BY_USERNAME_SUCCESSFULLY: 'FETCH_PRODUCTS_LIST_BY_USERNAME_SUCCESSFULLY',


    EDIT_PROFILE_LOADING: 'EDIT_PROFILE_LOADING',
    EDIT_PROFILE_FAILED: 'EDIT_PROFILE_FAILED',
    EDIT_PROFILE_REJECT: 'EDIT_PROFILE_REJECT',
    EDIT_PROFILE_SUCCESSFULLY: 'EDIT_PROFILE_SUCCESSFULLY',



    FETCH_ACCOUNT_BALANCE_LOADING: 'FETCH_ACCOUNT_BALANCE_LOADING',
    FETCH_ACCOUNT_BALANCE_FAILED: 'FETCH_ACCOUNT_BALANCE_FAILED',
    FETCH_ACCOUNT_BALANCE_REJECT: 'FETCH_ACCOUNT_BALANCE_REJECT',
    FETCH_ACCOUNT_BALANCE_SUCCESSFULLY: 'FETCH_ACCOUNT_BALANCE_SUCCESSFULLY',



    SET_PHONE_NUMBER_VIEW_PERMISSION_LOADING: 'SET_PHONE_NUMBER_VIEW_PERMISSION_LOADING',
    SET_PHONE_NUMBER_VIEW_PERMISSION_FAILED: 'SET_PHONE_NUMBER_VIEW_PERMISSION_FAILED',
    SET_PHONE_NUMBER_VIEW_PERMISSION_REJECT: 'SET_PHONE_NUMBER_VIEW_PERMISSION_REJECT',
    SET_PHONE_NUMBER_VIEW_PERMISSION_SUCCESSFULLY: 'SET_PHONE_NUMBER_VIEW_PERMISSION_SUCCESSFULLY',


    FETCH_USER_CONTACT_INFO_VIEWERS_LOADING: 'FETCH_USER_CONTACT_INFO_VIEWERS_LOADING',
    FETCH_USER_CONTACT_INFO_VIEWERS_FAILED: 'FETCH_USER_CONTACT_INFO_VIEWERS_FAILED',
    FETCH_USER_CONTACT_INFO_VIEWERS_REJECT: 'FETCH_USER_CONTACT_INFO_VIEWERS_REJECT',
    FETCH_USER_CONTACT_INFO_VIEWERS_SUCCESSFULLY: 'FETCH_USER_CONTACT_INFO_VIEWERS_SUCCESSFULLY',



    WALLET_ELEVATOR_PAY_LOADING: 'WALLET_ELEVATOR_PAY_LOADING',
    WALLET_ELEVATOR_PAY_FAILED: 'WALLET_ELEVATOR_PAY_FAILED',
    WALLET_ELEVATOR_PAY_REJECT: 'WALLET_ELEVATOR_PAY_REJECT',
    WALLET_ELEVATOR_PAY_SUCCESSFULLY: 'WALLET_ELEVATOR_PAY_SUCCESSFULLY',


    FETCH_ALL_PROFILE_INFO_LOADING: 'FETCH_ALL_PROFILE_INFO_LOADING',
    FETCH_ALL_PROFILE_INFO_FAILED: 'FETCH_ALL_PROFILE_INFO_FAILED',
    FETCH_ALL_PROFILE_INFO_REJECT: 'FETCH_ALL_PROFILE_INFO_REJECT',
    FETCH_ALL_PROFILE_INFO_SUCCESSFULLY: 'FETCH_ALL_PROFILE_INFO_SUCCESSFULLY',
}