export default {
    FETCH_ALL_CATEGORIES_LOADING: 'FETCH_ALL_CATEGORIES_LOADING',
    FETCH_ALL_CATEGORIES_SUCCESSFULLY: 'FETCH_ALL_CATEGORIES_SUCCESSFULLY',
    FETCH_ALL_CATEGORIES_FAILED: 'FETCH_ALL_CATEGORIES_FAILED',
    FETCH_ALL_CATEGORIES_REJECT: 'FETCH_ALL_CATEGORIES_REJECT',


    FETCH_ALL_SUB_CATEGORIES_LOADING: 'FETCH_ALL_SUB_CATEGORIES_LOADING',
    FETCH_ALL_SUB_CATEGORIES_SUCCESSFULLY: 'FETCH_ALL_SUB_CATEGORIES_SUCCESSFULLY',
    FETCH_ALL_SUB_CATEGORIES_FAILED: 'FETCH_ALL_SUB_CATEGORIES_FAILED',
    FETCH_ALL_SUB_CATEGORIES_REJECT: 'FETCH_ALL_SUB_CATEGORIES_REJECT',


    ADD_NEW_PRODUCT_LOADING: 'ADD_NEW_PRODUCT_LOADING',
    ADD_NEW_PRODUCT_SUCCESSFULLY: 'ADD_NEW_PRODUCT_SUCCESSFULLY',
    ADD_NEW_PRODUCT_FAILED: 'ADD_NEW_PRODUCT_FAILED',
    ADD_NEW_PRODUCT_REJECT: 'ADD_NEW_PRODUCT_REJECT',


    CHECK_USER_PERMISSION_TO_REGISTER_PRODUCT_LOADING: 'CHECK_USER_PERMISSION_TO_REGISTER_PRODUCT_LOADING',
    CHECK_USER_PERMISSION_TO_REGISTER_PRODUCT_SUCCESSFULLY: 'CHECK_USER_PERMISSION_TO_REGISTER_PRODUCT_SUCCESSFULLY',
    CHECK_USER_PERMISSION_TO_REGISTER_PRODUCT_FAILED: 'CHECK_USER_PERMISSION_TO_REGISTER_PRODUCT_FAILED',
    CHECK_USER_PERMISSION_TO_REGISTER_PRODUCT_REJECT: 'CHECK_USER_PERMISSION_TO_REGISTER_PRODUCT_REJECT',



    REGISTER_BUYAD_REQUEST_LOADING: 'REGISTER_BUYAD_REQUEST_LOADING',
    REGISTER_BUYAD_REQUEST_SUCCESSFULLY: 'REGISTER_BUYAD_REQUEST_SUCCESSFULLY',
    REGISTER_BUYAD_REQUEST_FAILED: 'REGISTER_BUYAD_REQUEST_FAILED',
    REGISTER_BUYAD_REQUEST_REJECT: 'REGISTER_BUYAD_REQUEST_REJECT',


    BUYADS_AFTER_PAYMENT_LOADING: 'BUYADS_AFTER_PAYMENT_LOADING',
    BUYADS_AFTER_PAYMENT_SUCCESSFULLY: 'BUYADS_AFTER_PAYMENT_SUCCESSFULLY',
    BUYADS_AFTER_PAYMENT_FAILED: 'BUYADS_AFTER_PAYMENT_FAILED',
    BUYADS_AFTER_PAYMENT_REJECT: 'BUYADS_AFTER_PAYMENT_REJECT',

    SET_PRODUCT_ID_FROM_REGISTER_PRODUCT: 'SET_PRODUCT_ID_FROM_REGISTER_PRODUCT',

    RESET_REGISTER_PRODUCT_TAB: 'RESET_REGISTER_PRODUCT_TAB',
};