export default {
    FETCH_ALL_CATEGORIES_LOADING: 'FETCH_ALL_CATEGORIES_LOADING',
    FETCH_ALL_CATEGORIES_SUCCESSFULLY: 'FETCH_ALL_CATEGORIES_SUCCESSFULLY',
    FETCH_ALL_CATEGORIES_FAILED: 'FETCH_ALL_CATEGORIES_FAILED',
    FETCH_ALL_CATEGORIES_REJECT: 'FETCH_ALL_CATEGORIES_REJECT',


    FETCH_ALL_SUB_CATEGORIES_LOADING: 'FETCH_ALL_SUB_CATEGORIES_LOADING',
    FETCH_ALL_SUB_CATEGORIES_SUCCESSFULLY: 'FETCH_ALL_SUB_CATEGORIES_SUCCESSFULLY',
    FETCH_ALL_SUB_CATEGORIES_FAILED: 'FETCH_ALL_SUB_CATEGORIES_FAILED',
    FETCH_ALL_SUB_CATEGORIES_REJECT: 'FETCH_ALL_SUB_CATEGORIES_REJECT',


};