export default {
    FETCH_ALL_CATEGORIES_LOADING: 'FETCH_ALL_CATEGORIES_LOADING',
    FETCH_ALL_CATEGORIES_SUCCESSFULLY: 'FETCH_ALL_CATEGORIES_SUCCESSFULLY',
    FETCH_ALL_CATEGORIES_FAILED: 'FETCH_ALL_CATEGORIES_FAILED',
    FETCH_ALL_CATEGORIES_REJECT: 'FETCH_ALL_CATEGORIES_REJECT',


    FETCH_ALL_SUB_CATEGORIES_LOADING: 'FETCH_ALL_SUB_CATEGORIES_LOADING',
    FETCH_ALL_SUB_CATEGORIES_SUCCESSFULLY: 'FETCH_ALL_SUB_CATEGORIES_SUCCESSFULLY',
    FETCH_ALL_SUB_CATEGORIES_FAILED: 'FETCH_ALL_SUB_CATEGORIES_FAILED',
    FETCH_ALL_SUB_CATEGORIES_REJECT: 'FETCH_ALL_SUB_CATEGORIES_REJECT',


    ADD_NEW_PRODUCT_LOADING: 'ADD_NEW_PRODUCT_LOADING',
    ADD_NEW_PRODUCT_SUCCESSFULLY: 'ADD_NEW_PRODUCT_SUCCESSFULLY',
    ADD_NEW_PRODUCT_FAILED: 'ADD_NEW_PRODUCT_FAILED',
    ADD_NEW_PRODUCT_REJECT: 'ADD_NEW_PRODUCT_REJECT',


    CHECK_USER_PERMISSION_TO_REGISTER_PRODUCT_LOADING: 'CHECK_USER_PERMISSION_TO_REGISTER_PRODUCT_LOADING',
    CHECK_USER_PERMISSION_TO_REGISTER_PRODUCT_SUCCESSFULLY: 'CHECK_USER_PERMISSION_TO_REGISTER_PRODUCT_SUCCESSFULLY',
    CHECK_USER_PERMISSION_TO_REGISTER_PRODUCT_FAILED: 'CHECK_USER_PERMISSION_TO_REGISTER_PRODUCT_FAILED',
    CHECK_USER_PERMISSION_TO_REGISTER_PRODUCT_REJECT: 'CHECK_USER_PERMISSION_TO_REGISTER_PRODUCT_REJECT',


};