export default {
    FETCH_BUYAD_REQUEST_LOADING: 'FETCH_BUYAD_REQUEST_LOADING',
    FETCH_BUYAD_REQUEST_FAILED: 'FETCH_BUYAD_REQUEST_FAILED',
    FETCH_BUYAD_REQUEST_REJECT: 'FETCH_BUYAD_REQUEST_REJECT',
    FETCH_BUYAD_REQUEST_SUCCESSFULLY: 'FETCH_BUYAD_REQUEST_SUCCESSFULLY',

    FETCH_RELATED_BUYAD_REQUESTS_LOADING: 'FETCH_RELATED_BUYAD_REQUESTS_LOADING',
    FETCH_RELATED_BUYAD_REQUESTS_FAILED: 'FETCH_RELATED_BUYAD_REQUESTS_FAILED',
    FETCH_RELATED_BUYAD_REQUESTS_REJECT: 'FETCH_RELATED_BUYAD_REQUESTS_REJECT',
    FETCH_RELATED_BUYAD_REQUESTS_SUCCESSFULLY: 'FETCH_RELATED_BUYAD_REQUESTS_SUCCESSFULLY',
}