export default {
    FETCH_BUYAD_REQUEST_LOADING: 'FETCH_BUYAD_REQUEST_LOADING',
    FETCH_BUYAD_REQUEST_FAILED: 'FETCH_BUYAD_REQUEST_FAILED',
    FETCH_BUYAD_REQUEST_REJECT: 'FETCH_BUYAD_REQUEST_REJECT',
    FETCH_BUYAD_REQUEST_SUCCESSFULLY: 'FETCH_BUYAD_REQUEST_SUCCESSFULLY',
}