export default {
    FETCH_BUYAD_REQUEST_LOADING: 'FETCH_BUYAD_REQUEST_LOADING',
    FETCH_BUYAD_REQUEST_FAILED: 'FETCH_BUYAD_REQUEST_FAILED',
    FETCH_BUYAD_REQUEST_REJECT: 'FETCH_BUYAD_REQUEST_REJECT',
    FETCH_BUYAD_REQUEST_SUCCESSFULLY: 'FETCH_BUYAD_REQUEST_SUCCESSFULLY',

    FETCH_RELATED_BUYAD_REQUESTS_LOADING: 'FETCH_RELATED_BUYAD_REQUESTS_LOADING',
    FETCH_RELATED_BUYAD_REQUESTS_FAILED: 'FETCH_RELATED_BUYAD_REQUESTS_FAILED',
    FETCH_RELATED_BUYAD_REQUESTS_REJECT: 'FETCH_RELATED_BUYAD_REQUESTS_REJECT',
    FETCH_RELATED_BUYAD_REQUESTS_SUCCESSFULLY: 'FETCH_RELATED_BUYAD_REQUESTS_SUCCESSFULLY',

    FETCH_MY_REQUESTS_LOADING: 'FETCH_MY_REQUESTS_LOADING',
    FETCH_MY_REQUESTS_FAILED: 'FETCH_MY_REQUESTS_FAILED',
    FETCH_MY_REQUESTS_REJECT: 'FETCH_MY_REQUESTS_REJECT',
    FETCH_MY_REQUESTS_SUCCESSFULLY: 'FETCH_MY_REQUESTS_SUCCESSFULLY',

    DELETE_BUYAD_LOADING: 'DELETE_BUYAD_LOADING',
    DELETE_BUYAD_FAILED: 'DELETE_BUYAD_FAILED',
    DELETE_BUYAD_REJECT: 'DELETE_BUYAD_REJECT',
    DELETE_BUYAD_SUCCESSFULLY: 'DELETE_BUYAD_SUCCESSFULLY',

    FETCH_BUYER_MOBILE_NUMBER_LOADING: 'FETCH_BUYER_MOBILE_NUMBER_LOADING',
    FETCH_BUYER_MOBILE_NUMBER_FAILED: 'FETCH_BUYER_MOBILE_NUMBER_FAILED',
    FETCH_BUYER_MOBILE_NUMBER_REJECT: 'FETCH_BUYER_MOBILE_NUMBER_REJECT',
    FETCH_BUYER_MOBILE_NUMBER_SUCCESSFULLY: 'FETCH_BUYER_MOBILE_NUMBER_SUCCESSFULLY',
}