export default {
    FETCH_ALL_PRODUCTS_LIST_LOADING: 'FETCH_ALL_PRODUCTS_LIST_LOADING',
    FETCH_ALL_PRODUCTS_LIST_SUCCESSFULLY: 'FETCH_ALL_PRODUCTS_LIST_SUCCESSFULLY',
    FETCH_ALL_PRODUCTS_LIST_FAILED: 'FETCH_ALL_PRODUCTS_LIST_FAILED',
    FETCH_ALL_PRODUCTS_LIST_REJECT: 'FETCH_ALL_PRODUCTS_LIST_REJECT',


    FETCH_ALL_RELATED_PRODUCTS_LIST_LOADING: 'FETCH_ALL_RELATED_PRODUCTS_LIST_LOADING',
    FETCH_ALL_RELATED_PRODUCTS_LIST_SUCCESSFULLY: 'FETCH_ALL_RELATED_PRODUCTS_LIST_SUCCESSFULLY',
    FETCH_ALL_RELATED_PRODUCTS_LIST_FAILED: 'FETCH_ALL_RELATED_PRODUCTS_LIST_FAILED',
    FETCH_ALL_RELATED_PRODUCTS_LIST_REJECT: 'FETCH_ALL_RELATED_PRODUCTS_LIST_REJECT',

    FETCH_ALL_MY_PRODUCTS_LOADING: 'FETCH_ALL_MY_PRODUCTS_LOADING',
    FETCH_ALL_MY_PRODUCTS_SUCCESSFULLY: 'FETCH_ALL_MY_PRODUCTS_SUCCESSFULLY',
    FETCH_ALL_MY_PRODUCTS_FAILED: 'FETCH_ALL_MY_PRODUCTS_FAILED',
    FETCH_ALL_MY_PRODUCTS_REJECT: 'FETCH_ALL_MY_PRODUCTS_REJECT',

    EDIT_PRODUCT_LOADING: 'EDIT_PRODUCT_LOADING',
    EDIT_PRODUCT_SUCCESSFULLY: 'EDIT_PRODUCT_SUCCESSFULLY',
    EDIT_PRODUCT_FAILED: 'EDIT_PRODUCT_FAILED',
    EDIT_PRODUCT_REJECT: 'EDIT_PRODUCT_REJECT',

    DELETE_PRODUCT_LOADING: 'DELETE_PRODUCT_LOADING',
    DELETE_PRODUCT_SUCCESSFULLY: 'DELETE_PRODUCT_SUCCESSFULLY',
    DELETE_PRODUCT_FAILED: 'DELETE_PRODUCT_FAILED',
    DELETE_PRODUCT_REJECT: 'DELETE_PRODUCT_REJECT',

    FETCH_PRODUCT_DETAILS_LOADING: 'FETCH_PRODUCT_DETAILS_LOADING',
    FETCH_PRODUCT_DETAILS_SUCCESSFULLY: 'FETCH_PRODUCT_DETAILS_SUCCESSFULLY',
    FETCH_PRODUCT_DETAILS_FAILED: 'FETCH_PRODUCT_DETAILS_FAILED',
    FETCH_PRODUCT_DETAILS_REJECT: 'FETCH_PRODUCT_DETAILS_REJECT',

    SET_PRODUCT_DETAILS_ID_LOADING: 'SET_PRODUCT_DETAILS_ID_LOADING',
    SET_PRODUCT_DETAILS_ID_SUCCESSFULLY: 'SET_PRODUCT_DETAILS_ID_SUCCESSFULLY',
    SET_PRODUCT_DETAILS_ID_FAILED: 'SET_PRODUCT_DETAILS_ID_FAILED',
    SET_PRODUCT_DETAILS_ID_REJECT: 'SET_PRODUCT_DETAILS_ID_REJECT',

};