export default {
    FETCH_ALL_PRODUCTS_LIST_LOADING: 'FETCH_ALL_PRODUCTS_LIST_LOADING',
    FETCH_ALL_PRODUCTS_LIST_SUCCESSFULLY: 'FETCH_ALL_PRODUCTS_LIST_SUCCESSFULLY',
    FETCH_ALL_PRODUCTS_LIST_FAILED: 'FETCH_ALL_PRODUCTS_LIST_FAILED',
    FETCH_ALL_PRODUCTS_LIST_REJECT: 'FETCH_ALL_PRODUCTS_LIST_REJECT',

    EDIT_PRODUCT_LOADING: 'EDIT_PRODUCT_LOADING',
    EDIT_PRODUCT_SUCCESSFULLY: 'EDIT_PRODUCT_SUCCESSFULLY',
    EDIT_PRODUCT_FAILED: 'EDIT_PRODUCT_FAILED',
    EDIT_PRODUCT_REJECT: 'EDIT_PRODUCT_REJECT',

    DELETE_PRODUCT_LOADING: 'DELETE_PRODUCT_LOADING',
    DELETE_PRODUCT_SUCCESSFULLY: 'DELETE_PRODUCT_SUCCESSFULLY',
    DELETE_PRODUCT_FAILED: 'DELETE_PRODUCT_FAILED',
    DELETE_PRODUCT_REJECT: 'DELETE_PRODUCT_REJECT',
};