export default {
    FETCH_ALL_PRODUCTS_LIST_LOADING: 'FETCH_ALL_PRODUCTS_LIST_LOADING',
    FETCH_ALL_PRODUCTS_LIST_SUCCESSFULLY: 'FETCH_ALL_PRODUCTS_LIST_SUCCESSFULLY',
    FETCH_ALL_PRODUCTS_LIST_FAILED: 'FETCH_ALL_PRODUCTS_LIST_FAILED',
    FETCH_ALL_PRODUCTS_LIST_REJECT: 'FETCH_ALL_PRODUCTS_LIST_REJECT',
};