export default {
    LOGIN_LOADING: 'LOGIN_LOADING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_REJECT: 'LOGIN_REJECT',

    CHECK_ALREADY_SIGNEDUP_MOBILE_NUMBER_LOADING: 'CHECK_ALREADY_SIGNEDUP_MOBILE_NUMBER_LOADING',
    CHECK_ALREADY_SIGNEDUP_MOBILE_NUMBER_SUCCESSFULLY: 'CHECK_ALREADY_SIGNEDUP_MOBILE_NUMBER_SUCCESSFULLY',
    CHECK_ALREADY_SIGNEDUP_MOBILE_NUMBER_FAILED: 'CHECK_ALREADY_SIGNEDUP_MOBILE_NUMBER_FAILED',
    CHECK_ALREADY_SIGNEDUP_MOBILE_NUMBER_REJECT: 'CHECK_ALREADY_SIGNEDUP_MOBILE_NUMBER_REJECT',

    CHECK_ACTIVISION_CODE_REJECT: 'CHECK_ACTIVISION_CODE_REJECT',
    CHECK_ACTIVISION_CODE_FAILED: 'CHECK_ACTIVISION_CODE_FAILED',
    CHECK_ACTIVISION_CODE_LOADING: 'CHECK_ACTIVISION_CODE_LOADING',
    CHECK_ACTIVISION_CODE_SUCCESSFULLY: 'CHECK_ACTIVISION_CODE_SUCCESSFULLY'
};