export default {
    LOGIN_LOADING: 'LOGIN_LOADING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_REJECT: 'LOGIN_REJECT',

    CHECK_ALREADY_SIGNEDUP_MOBILE_NUMBER_LOADING: 'CHECK_ALREADY_SIGNEDUP_MOBILE_NUMBER_LOADING',
    CHECK_ALREADY_SIGNEDUP_MOBILE_NUMBER_SUCCESSFULLY: 'CHECK_ALREADY_SIGNEDUP_MOBILE_NUMBER_SUCCESSFULLY',
    CHECK_ALREADY_SIGNEDUP_MOBILE_NUMBER_FAILED: 'CHECK_ALREADY_SIGNEDUP_MOBILE_NUMBER_FAILED',
    CHECK_ALREADY_SIGNEDUP_MOBILE_NUMBER_REJECT: 'CHECK_ALREADY_SIGNEDUP_MOBILE_NUMBER_REJECT',

    CHECK_ACTIVISION_CODE_REJECT: 'CHECK_ACTIVISION_CODE_REJECT',
    CHECK_ACTIVISION_CODE_FAILED: 'CHECK_ACTIVISION_CODE_FAILED',
    CHECK_ACTIVISION_CODE_LOADING: 'CHECK_ACTIVISION_CODE_LOADING',
    CHECK_ACTIVISION_CODE_SUCCESSFULLY: 'CHECK_ACTIVISION_CODE_SUCCESSFULLY',


    FETCH_ALL_ACTIVITIY_ZONE_REJECT: 'FETCH_ALL_ACTIVITIY_ZONE_REJECT',
    FETCH_ALL_ACTIVITIY_ZONE_FAILED: 'FETCH_ALL_ACTIVITIY_ZONE_FAILED',
    FETCH_ALL_ACTIVITIY_ZONE_LOADING: 'FETCH_ALL_ACTIVITIY_ZONE_LOADING',
    FETCH_ALL_ACTIVITIY_ZONE_SUCCESSFULLY: 'FETCH_ALL_ACTIVITIY_ZONE_SUCCESSFULLY',


    SUBMIT_REGISTER_REJECT: 'SUBMIT_REGISTER_REJECT',
    SUBMIT_REGISTER_FAILED: 'SUBMIT_REGISTER_FAILED',
    SUBMIT_REGISTER_LOADING: 'SUBMIT_REGISTER_LOADING',
    SUBMIT_REGISTER_SUCCESSFULLY: 'SUBMIT_REGISTER_SUCCESSFULLY',



    CHANGE_ROLE_REJECT: 'CHANGE_ROLE_REJECT',
    CHANGE_ROLE_FAILED: 'CHANGE_ROLE_FAILED',
    CHANGE_ROLE_LOADING: 'CHANGE_ROLE_LOADING',
    CHANGE_ROLE_SUCCESSFULLY: 'CHANGE_ROLE_SUCCESSFULLY',


    LOGOUT_REJECT: 'LOGOUT_REJECT',
    LOGOUT_FAILED: 'LOGOUT_FAILED',
    LOGOUT_LOADING: 'LOGOUT_LOADING',
    LOGOUT_SUCCESSFULLY: 'LOGOUT_SUCCESSFULLY',


    SET_EVIDENCES_REJECT: 'SET_EVIDENCES_REJECT',
    SET_EVIDENCES_FAILED: 'SET_EVIDENCES_FAILED',
    SET_EVIDENCES_LOADING: 'SET_EVIDENCES_LOADING',
    SET_EVIDENCES_SUCCESSFULLY: 'SET_EVIDENCES_SUCCESSFULLY',
};