export default {
    FETCH_ALL_DASHBOARD_DATA_LOADING: 'FETCH_ALL_DASHBOARD_DATA_LOADING',
    FETCH_ALL_DASHBOARD_DATA_SUCCESSFULLY: 'FETCH_ALL_DASHBOARD_DATA_SUCCESSFULLY',
    FETCH_ALL_DASHBOARD_DATA_FAILED: 'FETCH_ALL_DASHBOARD_DATA_FAILED',
    FETCH_ALL_DASHBOARD_DATA_REJECT: 'FETCH_ALL_DASHBOARD_DATA_REJECT',

    FETCH_PACKAGES_PRICES_LOADING: 'FETCH_PACKAGES_PRICES_LOADING',
    FETCH_PACKAGES_PRICES_SUCCESSFULLY: 'FETCH_PACKAGES_PRICES_SUCCESSFULLY',
    FETCH_PACKAGES_PRICES_FAILED: 'FETCH_PACKAGES_PRICES_FAILED',
    FETCH_PACKAGES_PRICES_REJECT: 'FETCH_PACKAGES_PRICES_REJECT',
};