export default {
    FETCH_ALL_DASHBOARD_DATA_LOADING: 'FETCH_ALL_DASHBOARD_DATA_LOADING',
    FETCH_ALL_DASHBOARD_DATA_SUCCESSFULLY: 'FETCH_ALL_DASHBOARD_DATA_SUCCESSFULLY',
    FETCH_ALL_DASHBOARD_DATA_FAILED: 'FETCH_ALL_DASHBOARD_DATA_FAILED',
    FETCH_ALL_DASHBOARD_DATA_REJECT: 'FETCH_ALL_DASHBOARD_DATA_REJECT',
};