export default {
    FETCH_ALL_COMMENTS_LOADING: 'FETCH_ALL_COMMENTS_LOADING',
    FETCH_ALL_COMMENTS_FAILED: 'FETCH_ALL_COMMENTS_FAILED',
    FETCH_ALL_COMMENTS_REJECT: 'FETCH_ALL_COMMENTS_REJECT',
    FETCH_ALL_COMMENTS_SUCCESSFULLY: 'FETCH_ALL_COMMENTS_SUCCESSFULLY',

    CHECK_USER_AUTHORITY_TO_POST_COMMENT_LOADING: 'CHECK_USER_AUTHORITY_TO_POST_COMMENT_LOADING',
    CHECK_USER_AUTHORITY_TO_POST_COMMENT_FAILED: 'CHECK_USER_AUTHORITY_TO_POST_COMMENT_FAILED',
    CHECK_USER_AUTHORITY_TO_POST_COMMENT_REJECT: 'CHECK_USER_AUTHORITY_TO_POST_COMMENT_REJECT',
    CHECK_USER_AUTHORITY_TO_POST_COMMENT_SUCCESSFULLY: 'CHECK_USER_AUTHORITY_TO_POST_COMMENT_SUCCESSFULLY',

    LIKE_OR_DISLIKE_COMMENT_LOADING: 'LIKE_OR_DISLIKE_COMMENT_LOADING',
    LIKE_OR_DISLIKE_COMMENT_FAILED: 'LIKE_OR_DISLIKE_COMMENT_FAILED',
    LIKE_OR_DISLIKE_COMMENT_REJECT: 'LIKE_OR_DISLIKE_COMMENT_REJECT',
    LIKE_OR_DISLIKE_COMMENT_SUCCESSFULLY: 'LIKE_OR_DISLIKE_COMMENT_SUCCESSFULLY',

    DELETE_COMMENT_LOADING: 'DELETE_COMMENT_LOADING',
    DELETE_COMMENT_FAILED: 'DELETE_COMMENT_FAILED',
    DELETE_COMMENT_REJECT: 'DELETE_COMMENT_REJECT',
    DELETE_COMMENT_SUCCESSFULLY: 'DELETE_COMMENT_SUCCESSFULLY',

    SUBMIT_RATING_LOADING: 'SUBMIT_RATING_LOADING',
    SUBMIT_RATING_FAILED: 'SUBMIT_RATING_FAILED',
    SUBMIT_RATING_REJECT: 'SUBMIT_RATING_REJECT',
    SUBMIT_RATING_SUCCESSFULLY: 'SUBMIT_RATING_SUCCESSFULLY',
}