export default {
    FETCH_ALL_COMMENTS_LOADING: 'FETCH_ALL_COMMENTS_LOADING',
    FETCH_ALL_COMMENTS_FAILED: 'FETCH_ALL_COMMENTS_FAILED',
    FETCH_ALL_COMMENTS_REJECT: 'FETCH_ALL_COMMENTS_REJECT',
    FETCH_ALL_COMMENTS_SUCCESSFULLY: 'FETCH_ALL_COMMENTS_SUCCESSFULLY',
}