export default {
    FETCH_ALL_PROVINCES_LOADING: 'FETCH_ALL_PROVINCES_LOADING',
    FETCH_ALL_PROVINCES_SUCCESSFULLY: 'FETCH_ALL_PROVINCES_SUCCESSFULLY',
    FETCH_ALL_PROVINCES_FAILED: 'FETCH_ALL_PROVINCES_FAILED',
    FETCH_ALL_PROVINCES_REJECT: 'FETCH_ALL_PROVINCES_REJECT',

    FETCH_ALL_CITIES_LOADING: 'FETCH_ALL_CITIES_LOADING',
    FETCH_ALL_CITIES_SUCCESSFULLY: 'FETCH_ALL_CITIES_SUCCESSFULLY',
    FETCH_ALL_CITIES_FAILED: 'FETCH_ALL_CITIES_FAILED',
    FETCH_ALL_CITIES_REJECT: 'FETCH_ALL_CITIES_REJECT',
}